config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :authors, :controllers => { registrations: 'registrations' }
  root to: 'blog/books#index'

  namespace :authors do
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
  	resources :books do
      member do 
        put 'publish' => 'books#publish'
        put 'unpublish' => 'books#unpublish'
      end
    end
  end

  namespace :blog do
    resources :tags, only: [:index, :show]
    resources :books, only: [:show, :index]
  end

  # scope module: 'blog' do
  # 	get 'books' => 'books#index', as: :books
  # 	get 'books/:id' => 'books#show', as: :post
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
# == Schema Information
#
# Table name: posts
#
#  id                 :integer          not null, primary key
#  name               :string
#  content            :text
#  slug               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  author_id          :integer
#  published          :boolean
#  published_at       :datetime
#

class Book < ApplicationRecord
  paginates_per 6
  acts_as_taggable

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :author

  validates_presence_of :name
  validates_presence_of :content

  scope :most_recent, -> { order(published_at: :desc) }
  scope :last_week, -> { where("published_at >= :date", :date => 1.week.ago) }
  scope :published, -> { where(published: true) }
  

  has_attached_file :image, styles: { medium: "700x400>", thumb: "350x200>" }, default_url: "Flag_missing.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def should_generate_new_friendly_id?
    name_changed?
  end

  def display_day_published
    if published_at.present?
  	  published_at.strftime('%-b %-d, %-Y')
    else
      "Not published"
    end
  end

  def owner?(user)
    self.author == user
  end
end

app/controllers/authors/books_controller.rb
class Authors::BooksController < AuthorController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

  def index
    @books = current_author.books.most_recent
  end

  def show
  end

  def new
    @book = current_author.books.new
  end

  def edit
  end

  def publish
    @book.update(published: true, published_at: Time.now)
    redirect_to authors_books_url
  end

  def unpublish
    @book.update(published: false, published_at: nil)
    redirect_to authors_books_url
  end

  def create
    @book = current_author.books.new(post_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to authors_book_path(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(post_params)
        format.html { redirect_to authors_book_path(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to authors_books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = current_author.books.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:book).permit(:author_name, :name, :content, :image, :tag_list, :tag, { tag_ids: [] }, :tag_ids)
  end
end

app/controllers/blog/books_controller.rb
class Blog::BooksController < BlogController

  def index
 	  if params[:category].present?
      @books = last_week_published.tagged_with(params[:category]).page params[:page]
 	  else
      @books = last_week_published.page params[:page]
    end
  end

  def show
    puts last_week_published.inspect
    if !last_week_published.blank?
      @book = last_week_published.friendly.find(params[:id])
    else
      redirect_to root_path, notice: 'Book was published more than one week ago'
    end
  end

  private

  def last_week_published
  	Book.published.last_week.most_recent
  end
end

app/controllers/blog/tags_controller.rb
class Blog::TagsController < BlogController

  def index
    @categories = Tag.order("taggings_count DESC").search(params[:search]).page params[:page]
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/views/blog/books/_book.html.erb
<div class='col-sm-6 col-lg-4'>
  <div class="card">
    <%= link_to blog_book_path(book) do %>
      <div class="card-topper"><%= image_tag book.image.url(:thumb) %></div>
    <% end %>
    <div class="card-block">
    <h6 class="published-date pull-right"><%= book.author.name %></h6>
      <h4 class="card-title"><%= link_to book.name, blog_book_path(book) %></h4>
      <p><%= raw book.tags.map { |t| link_to t.name, root_path(category: t.name) }.join(', ') %></p>
      <h6 class="published-date"><%= book.display_day_published %></h6>
      <p class="card-text"><%= truncate_html(book.content, length: 130) %></p>
    </div>
  </div>
</div>

app/views/blog/books/index.html.erb
<% provide(:page_title, 'Books') %>
<% provide(:blog_active, 'active') %>

<div class="row">	
  <%= render @books %>
</div>

<div class="apple_pagination">
  <%= paginate @books, container: false %>
</div>

app/views/blog/books/show.html.erb
<% provide(:page_title, @book.name) %>
<% provide(:blog_active, 'active') %>

<% if @book.owner?(current_author) %>
  <div>
    <%= link_to "Edit", edit_authors_book_path(@book), class: 'btn btn-sm btn-warning' %>
    <%= link_to "Remove", authors_book_path(@book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
    <% if @book.published? %>
      <%= link_to "To draft", unpublish_authors_book_path(@book), method: :put, class: 'btn btn-sm btn-primary' %>
    <% else %>
      <%= link_to "Publish", publish_authors_book_path(@book), method: :put, class: 'btn btn-sm btn-success' %>
    <% end %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <% if !@book.image.nil? %>
      <div class="text-center">
        <%= image_tag @book.image.url(:medium), class: "book-image" %>
      </div>
    <% end %>
    <hr>
    <h1 class="text-center"><b><%= @book.name %></b></h1>
    <hr>
    <p class="publish pull-right"><%= @book.author.name %></p>
    <p class="publish"><%= @book.display_day_published %></p>
    <%= @book.content.html_safe %>
    <hr>
  </div>
</div>