config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :authors, :controllers => { registrations: 'registrations' }
  root to: 'blog/books#index'

  namespace :authors do
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
  	resources :books do
      member do 
        put 'publish' => 'books#publish'
        put 'unpublish' => 'books#unpublish'
      end
    end
  end

  namespace :blog do
    resources :tags, only: [:index, :show]
    resources :books, only: [:show, :index]
  end

  # scope module: 'blog' do
  # 	get 'books' => 'books#index', as: :books
  # 	get 'books/:id' => 'books#show', as: :post
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_tagger    

  has_many :books, dependent: :destroy

  has_attached_file :avatar, styles: { medium: "200x200#", thumb: "100x100#" }, default_url: "missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  before_save :capitalize_name

  def capitalize_name
    if !self.name.nil?
      self.name = self.name.titleize
    end
  end

  def update_without_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end  
end

app/models/tag.rb
class Tag < ApplicationRecord
  paginates_per 6
  
  validates_uniqueness_of :name
  validates_presence_of :name

  before_save :capitalize_name

  def capitalize_name
    if !self.name.nil?
      self.name = self.name.titleize
    end
  end

  def self.search(search)
    if search
      where('name ILIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
	before_action :authenticate_author!
end

app/controllers/authors/books_controller.rb
class Authors::BooksController < AuthorController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

  def index
    @books = current_author.books.most_recent
  end

  def show
  end

  def new
    @book = current_author.books.new
  end

  def edit
  end

  def publish
    @book.update(published: true, published_at: Time.now)
    redirect_to authors_books_url
  end

  def unpublish
    @book.update(published: false, published_at: nil)
    redirect_to authors_books_url
  end

  def create
    @book = current_author.books.new(post_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to authors_book_path(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(post_params)
        format.html { redirect_to authors_book_path(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to authors_books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = current_author.books.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:book).permit(:author_name, :name, :content, :image, :tag_list, :tag, { tag_ids: [] }, :tag_ids)
  end
end

app/controllers/authors/tags_controller.rb
class Authors::TagsController < AuthorController

  def create
    @tag = Tag.where(tag_params).first_or_create
    respond_to do |format|
      if @tag.save
        format.json { render json: @tag }
        format.html { redirect_to blog_tags_path, notice: 'Category was successfully created' }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to blog_tags_path, notice: 'Category was successfully updated' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to blog_tags_url, notice: 'Category was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :description)
    end
end

app/controllers/blog/tags_controller.rb
class Blog::TagsController < BlogController

  def index
    @categories = Tag.order("taggings_count DESC").search(params[:search]).page params[:page]
  end
end

app/views/authors/tags/_form.html.erb
<%= form_for(tag, url: url) do |f| %>

  <% if tag.errors.any? %>
    <div class="col-md-6 offset-md-3 alert alert-info">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 offset-md-3">
        
        <div class="form-login">
          <%= f.text_field :name, autofocus: true, class: "form-control input-sm chat-input", placeholder: "name" %>
          </br>
          <%= f.text_area :description, class: "form-control input-sm chat-input", placeholder: "description" %>
          </br>
          <div class="wrapper">
            <span class="group-btn"> 
                <%= f.submit "save", class: "btn btn-primary btn-md" %>
            </span>
          </div>
        </div>
    </div>
  </div>
<% end %>

app/views/authors/tags/edit.html.erb
<% provide(:page_title, "Edit #{@tag.name}") %>
<% provide(:categories, 'active') %>

<div class="row text-center">
  <div class="col-md-6 offset-md-3">
	<h2><b>Edit</b> <%= "'#{@tag.name}'" %></h2>
  </div>
</div>

<%= render 'form', tag: @tag, url: authors_tag_path(@tag) %>

app/views/authors/tags/new.html.erb
<% provide(:page_title, "New category") %>
<% provide(:categories, 'active') %>

<div class="row text-center">
  <div class="col-md-6 offset-md-3">
	<h2>New category</h2>
  </div>
</div>

<%= render 'form', tag: @tag, url: authors_tags_path %>