config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :authors, :controllers => { registrations: 'registrations' }
  root to: 'blog/books#index'

  namespace :authors do
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
  	resources :books do
      member do 
        put 'publish' => 'books#publish'
        put 'unpublish' => 'books#unpublish'
      end
    end
  end

  namespace :blog do
    resources :tags, only: [:index, :show]
    resources :books, only: [:show, :index]
  end

  # scope module: 'blog' do
  # 	get 'books' => 'books#index', as: :books
  # 	get 'books/:id' => 'books#show', as: :post
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_tagger    

  has_many :books, dependent: :destroy

  has_attached_file :avatar, styles: { medium: "200x200#", thumb: "100x100#" }, default_url: "missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  before_save :capitalize_name

  def capitalize_name
    if !self.name.nil?
      self.name = self.name.titleize
    end
  end

  def update_without_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end  
end

app/models/book.rb
# == Schema Information
#
# Table name: posts
#
#  id                 :integer          not null, primary key
#  name               :string
#  content            :text
#  slug               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  author_id          :integer
#  published          :boolean
#  published_at       :datetime
#

class Book < ApplicationRecord
  paginates_per 6
  acts_as_taggable

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :author

  validates_presence_of :name
  validates_presence_of :content

  scope :most_recent, -> { order(published_at: :desc) }
  scope :last_week, -> { where("published_at >= :date", :date => 1.week.ago) }
  scope :published, -> { where(published: true) }
  

  has_attached_file :image, styles: { medium: "700x400>", thumb: "350x200>" }, default_url: "Flag_missing.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def should_generate_new_friendly_id?
    name_changed?
  end

  def display_day_published
    if published_at.present?
  	  published_at.strftime('%-b %-d, %-Y')
    else
      "Not published"
    end
  end

  def owner?(user)
    self.author == user
  end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
	before_action :authenticate_author!
end

app/controllers/authors/books_controller.rb
class Authors::BooksController < AuthorController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

  def index
    @books = current_author.books.most_recent
  end

  def show
  end

  def new
    @book = current_author.books.new
  end

  def edit
  end

  def publish
    @book.update(published: true, published_at: Time.now)
    redirect_to authors_books_url
  end

  def unpublish
    @book.update(published: false, published_at: nil)
    redirect_to authors_books_url
  end

  def create
    @book = current_author.books.new(post_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to authors_book_path(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(post_params)
        format.html { redirect_to authors_book_path(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to authors_books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = current_author.books.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:book).permit(:author_name, :name, :content, :image, :tag_list, :tag, { tag_ids: [] }, :tag_ids)
  end
end

app/controllers/authors/tags_controller.rb
class Authors::TagsController < AuthorController

  def create
    @tag = Tag.where(tag_params).first_or_create
    respond_to do |format|
      if @tag.save
        format.json { render json: @tag }
        format.html { redirect_to blog_tags_path, notice: 'Category was successfully created' }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to blog_tags_path, notice: 'Category was successfully updated' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to blog_tags_url, notice: 'Category was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :description)
    end
end

app/controllers/blog/books_controller.rb
class Blog::BooksController < BlogController

  def index
 	  if params[:category].present?
      @books = last_week_published.tagged_with(params[:category]).page params[:page]
 	  else
      @books = last_week_published.page params[:page]
    end
  end

  def show
    puts last_week_published.inspect
    if !last_week_published.blank?
      @book = last_week_published.friendly.find(params[:id])
    else
      redirect_to root_path, notice: 'Book was published more than one week ago'
    end
  end

  private

  def last_week_published
  	Book.published.last_week.most_recent
  end
end

app/views/authors/books/_book.html.erb
<tr>
  <td><%= link_to book.name, authors_book_path(book) %></td>
  <td><%= raw book.tags.map { |t| link_to t.name, root_path(category: t.name) }.join(', ') %></td>
  <td></td>
  <% if book.published? %>
  	<td><%= link_to "To draft", unpublish_authors_book_path(book), method: :put, class: 'btn btn-sm btn-primary' %></td>
  <% else %>
  	<td><%= link_to "Publish", publish_authors_book_path(book), method: :put, class: 'btn btn-sm btn-success' %></td>
  <% end %>
  <td><%= link_to "Edit", edit_authors_book_path(book), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to "Remove", authors_book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/authors/books/_form.html.erb
<%= tinymce %>
<%= form_for(book, url: url) do |f| %>

  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-3 text-center">

      <div class="card text-center">
        <div class="card-block">
          <% if @book.new_record? %>
            <h4 class="card-title">New book</h4>
          <% else %>
            <h4 class="card-title">
              <b>Edit</b>
              <span class="thin-text"><%= "'#{@book.name}'" %></span>
            </h4>
          <% end %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <%= f.label :title %>
            <%= f.text_field :name, class: 'form-control' %>
          </li>
          <li class="list-group-item">
            <%= f.label 'Categories' %>
            <%= f.collection_select :tag_ids, Tag.order(:name), :id, :name, {}, {multiple: true, class: 'selectize'} %>
          </li>
          <li class="list-group-item">
            <%= f.file_field :image %>
          </li>
        </ul>

        <div class="list-group-item">
          <%= f.submit "Save", class: 'btn btn-success btn-lg', id: 'submit-book' %>
        </div>
      </div>

      <% if @book.persisted? %>
        <%= link_to 'Show', authors_book_path(@book) %> |
      <% end %>

      <%= link_to 'Back', authors_books_path %>
    </div>
    <div class="col-md-9">
      <div class="field">
        <%= f.text_area :content, class: "tinymce", rows: 20, cols: 80 %>
      </div>
    </div>
  </div>
<% end %>

<div class="modal fade category-modal tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">*</span></button>
        <h4 class="modal-title" id="mySmallModalLabel">Add category</h4>
      </div>
      <div class="modal-body">
        <%= form_for Tag.new, url: authors_tags_path do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.submit "Create category", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/books/edit.html.erb
<% provide(:page_title, "Edit #{@book.name}") %>
<% provide(:author, 'active') %>
<%= tinymce_assets %>
<%= render 'form', book: @book, url: authors_book_url(@book) %>

app/views/authors/books/index.html.erb
<% provide(:page_title, 'Books') %>
<% provide(:author, 'active') %>

<div class="row">
  <div style="margin-bottom: 2%;">
    <%= link_to 'New book', new_authors_book_path, class: 'btn btn-primary btn-lg' %>
  </div>
	<table class="table table-striped">
    <tr>
      <th>Title</th>
      <th colspan="2">Categories</th>
      <th colspan="3">Actions</th>
    </tr>
    <%= render @books %>
  </table>
</div>

app/views/authors/books/new.html.erb
<% provide(:page_title, 'New book') %>
<% provide(:author, 'active') %>

<%= render 'form', book: @book, url: authors_books_url %>

app/views/authors/books/show.html.erb
<% provide(:page_title, @book.name) %>
<% provide(:author, 'active') %>

<div>
  <%= link_to "Edit", edit_authors_book_path(@book), class: 'btn btn-sm btn-warning' %>
  <%= link_to "Remove", authors_book_path(@book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  <% if @book.published? %>
    <%= link_to "To draft", unpublish_authors_book_path(@book), method: :put, class: 'btn btn-sm btn-primary' %>
  <% else %>
    <%= link_to "Publish", publish_authors_book_path(@book), method: :put, class: 'btn btn-sm btn-success' %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <% if !@book.image.nil? %>
      <div class="text-center">
        <%= image_tag @book.image.url(:medium), class: "book-image" %>
      </div>
    <% end %>
    <hr>
    <h1 class="text-center"><b><%= @book.name %></b></h1>
    <hr>
    <p class="publish"><%= @book.display_day_published %></p>
    <%= @book.content.html_safe %>
    <hr>
  </div>
</div>