config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :authors, :controllers => { registrations: 'registrations' }
  root to: 'blog/books#index'

  namespace :authors do
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
  	resources :books do
      member do 
        put 'publish' => 'books#publish'
        put 'unpublish' => 'books#unpublish'
      end
    end
  end

  namespace :blog do
    resources :tags, only: [:index, :show]
    resources :books, only: [:show, :index]
  end

  # scope module: 'blog' do
  # 	get 'books' => 'books#index', as: :books
  # 	get 'books/:id' => 'books#show', as: :post
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href='/'>Sloboda<span class='light'>studio</span></a>

    <div class="collapse navbar-collapse pull-right" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto pull-left">
        <li class="nav-item">
          <%= link_to 'All categories', blog_tags_path, class: "nav-link #{yield(:categories)}" %>
        </li>
      </ul>
      <ul class="navbar-nav pull-right">
        <% if author_signed_in? %>
          <li class="nav-item" id="round-image-30">
            <%= image_tag current_author.avatar.url(:thumb) %>
          </li>
          <li class="nav-item">
            <% if !current_author.name.blank? %>
              <%= link_to current_author.name, edit_author_registration_path, class: "nav-link #{yield(:edit)}" %>
            <% else %>
              <%= link_to 'My profile', edit_author_registration_path, class: "nav-link #{yield(:edit)}" %>
            <% end %> 
          </li>
          <li class="nav-item">
            <%= link_to 'My books', authors_books_path, class: "nav-link #{yield(:author)}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_author_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Register', new_author_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in', new_author_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title)%> | MassMedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

  	<div class="container <%= controller_name %> <%= action_name %>" >

      <%- if flash.any? %>
        <% flash.each do |name, msg| %>
          <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <%= msg %>
          </div>
        <% end %>
      <% end %> 
      
    	<%= yield %>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title)%> | MassMedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
  	<div class="container <%= controller_name %> <%= action_name %>" >
    	<%= yield %>
    </div>
  </body>
</html>